#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if package.json has changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "package.json"; then
  echo "📦 package.json changed. Installing dependencies..."
  pnpm install
fi 